#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Todo.Android.Resource", IsApplication=true)]

namespace Todo.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Gcm.Client.Resource.String.library_name = global::Todo.Android.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Todo.Android.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Todo.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int check = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int check2x = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int facebook_fat = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int LogoMindSet128x128 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int LogoMindSet32 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int LogoMindSet48x48 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Move = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int reorder = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int save = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int SignInGoogle = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int speak = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Task25pComplete64 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Task50pComplete64 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Task75pComplete64 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int TaskCancelled64 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int TaskCompleted64 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int TaskConceived64 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int TaskNotStarted64 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int TaskOnHold64 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int TaskStarted64 = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int icon1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int months_list = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int myButton = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int textview = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textview1 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int listitem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
